linter:
  rules:
    - avoid_print
analyzer:
  errors:
    deprecated_member_use: ignore
    unused_local_variable: ignore
    unused_field: ignore
    unused_import: ignore
    no_leading_underscores_for_local_identifiers: ignore
    unnecessary_brace_in_string_interps: ignore
