name: Build & Upload APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.9'
      - run: flutter pub get
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/nafahat-release.keystore
      - run: flutter build apk --debug
      - name: Upload APK and get direct link
        run: |
          echo "Uploading APK to 0x0.st..."
          URL=$(curl -s -F "file=@build/app/outputs/flutter-apk/app-debug.apk" https://0x0.st)
          echo "Download link: $URL"
          echo "LINK=$URL" >> $GITHUB_ENV
      - name: Show link in summary
        run: echo "### 📱 Download APK :rocket: [Click here](${{ env.LINK }})" >> $GITHUB_STEP_SUMMARY
